//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMobilProgramlama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int ilplaka { get; set; }
        public string ilad { get; set; }
    }
}
